version: '3.1'

services:

  app:
    build: ./src
    depends_on: 
      - db
    volumes: 
      - ./src:/usr/src/app

  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: database
    ports: 
        - 5432:5432
